CREATE TABLE IF NOT EXISTS "registrations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "member_id" text NOT NULL UNIQUE,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "middle_initial" text,
  "age" integer NOT NULL,
  "gender" text NOT NULL,
  "date_of_birth" text NOT NULL,
  "place_of_birth" text NOT NULL,
  "street" text NOT NULL,
  "barangay" text NOT NULL,
  "municipality" text NOT NULL,
  "province" text NOT NULL,
  "guardian_name" text NOT NULL,
  "guardian_address" text NOT NULL,
  "guardian_contact" text NOT NULL,
  "guardian_relationship" text NOT NULL,
  "studying" text NOT NULL,
  "school_name" text NOT NULL,
  "school_address" text,
  "school_year" text,
  "educational_attainment" text,
  "email" text NOT NULL UNIQUE,
  "contact_number" text NOT NULL,
  "password_hash" text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL
);
