CREATE TABLE IF NOT EXISTS "pgpmembers" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "member_id" text NOT NULL,
  "first_name" text NOT NULL,
  "last_name" text NOT NULL,
  "middle_initial" text,
  "age" integer NOT NULL,
  "date_of_birth" text NOT NULL,
  "place_of_birth" text NOT NULL,
  "street" text NOT NULL,
  "barangay" text NOT NULL,
  "municipality" text NOT NULL,
  "province" text NOT NULL,
  "email" text NOT NULL,
  "contact_number" text NOT NULL,
  "guardian_name" text NOT NULL,
  "guardian_address" text NOT NULL,
  "guardian_contact" text NOT NULL,
  "baptized_name" text NOT NULL,
  "date_survived" text NOT NULL,
  "status" text NOT NULL,
  "officer_position" text,
  "officer_date_elected" text,
  "former_president_start" text,
  "former_president_end" text,
  "grand_knight" text,
  "photo_url" text,
  "has_photo" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "pgpmembers_member_id_unique" UNIQUE("member_id")
);