import type { Metadata } from "next";
import Image from "next/image";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { pgpmembers } from "@/db/schema";
import { getRegistrationStatus } from "@/lib/neophyte-auth";
import PublicPrintButton from "@/components/public-print-button";

export const metadata: Metadata = { title: "Certificate of Confirmation" };
export const dynamic = "force-dynamic";

export default async function PublicCertificatePage() {
  const registration = await getRegistrationStatus();
  if (!registration) return <main className="flex min-h-screen items-center justify-center bg-[#f1eee4] px-5 text-center"><div><h1 className="font-serif text-3xl font-semibold text-[var(--green-dark)]">Sign in required</h1><p className="mt-2 text-sm text-black/60">Please sign in to the neophyte portal to view your certificate.</p><a href="/join/status" className="mt-5 inline-flex rounded-sm bg-[var(--green)] px-5 py-3 text-sm font-semibold text-white">Return to portal</a></div></main>;
  const [member] = await db.select().from(pgpmembers).where(eq(pgpmembers.email, registration.email)).limit(1);
  if (!member?.neophyteCertificationIssuedAt) return <main className="flex min-h-screen items-center justify-center bg-[#f1eee4] px-5 text-center"><div><h1 className="font-serif text-3xl font-semibold text-[var(--green-dark)]">Certificate not ready</h1><p className="mt-2 text-sm text-black/60">Your certificate will be available after the chapter issues it.</p><a href="/join/status" className="mt-5 inline-flex rounded-sm border border-black/15 px-5 py-3 text-sm font-semibold text-black/65">Return to portal</a></div></main>;

  const name = `${member.firstName}${member.middleInitial ? ` ${member.middleInitial}.` : ""} ${member.lastName}`;
  const issuedDate = member.neophyteCertificationIssuedAt.toLocaleDateString("en-PH", { day: "numeric", month: "long", year: "numeric" });
  return <main className="min-h-screen bg-[#f1eee4] px-4 py-8 text-[var(--green-dark)] print:bg-white print:p-0 sm:px-8"><div className="mx-auto max-w-4xl"><div className="mb-4 flex items-center justify-between print:hidden"><a href="/join/status" className="text-sm font-semibold text-[var(--green)]">← Back to portal</a><PublicPrintButton /></div><article className="border-[10px] border-double border-[var(--green-dark)] bg-white px-7 py-10 text-center shadow-[0_18px_45px_rgba(15,61,38,0.12)] sm:px-16 sm:py-14 print:min-h-screen print:shadow-none"><Image src="/PI GAMMA PHI.png" width={90} height={90} alt="Pi Gamma Phi logo" className="mx-auto h-20 w-20 object-contain" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.28em] text-[var(--gold)]">Pi Gamma Phi 1975 · Gamma Sigma</p><p className="mt-1 text-xs uppercase tracking-[0.18em] text-black/50">Roxas City Capiz Chapter</p><div className="mx-auto mt-9 max-w-2xl border-y border-[var(--gold)]/60 py-6"><h1 className="font-serif text-4xl font-semibold tracking-tight text-[var(--green-dark)] sm:text-5xl">Certificate of Confirmation</h1><p className="mt-3 text-sm leading-6 text-black/65">This is to certify that</p><p className="mt-3 text-3xl font-semibold text-[var(--green)] sm:text-4xl">{name}</p><p className="mt-4 text-sm leading-6 text-black/65">has completed the required neophyte formation stages and is welcomed as a new member of Pi Gamma Phi Gamma Sigma, Roxas City Capiz Chapter.</p></div><div className="mx-auto mt-8 max-w-lg text-left"><p className="text-center text-xs font-semibold uppercase tracking-[0.16em] text-black/45">Formation completed</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{["Orientation", "Baptism", "Confirmation of Baptism", "Welcome as a new member"].map((item) => <li key={item} className="flex items-center gap-2 text-sm text-black/70"><span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-[var(--green-soft)] text-xs font-bold text-[var(--green)]">✓</span>{item}</li>)}</ul></div><div className="mt-12 grid gap-8 text-left text-xs text-black/55 sm:grid-cols-2"><div className="border-t border-black/30 pt-2"><p>Issued {issuedDate}</p><p className="mt-1">Certificate holder · {member.memberId}</p></div><div className="border-t border-black/30 pt-2"><p>Issued by</p><p className="mt-1">{member.neophyteCertificationIssuedBy ?? "Chapter administration"}</p></div></div></article></div></main>;
}
